package com.ceq.dao;

import com.ceq.app.core.bean.Bean_Properties;
import com.ceq.app.core.bean.Bean_UserInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bean_PropertiesDaoConfig;
    private final DaoConfig bean_UserInfoDaoConfig;

    private final Bean_PropertiesDao bean_PropertiesDao;
    private final Bean_UserInfoDao bean_UserInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bean_PropertiesDaoConfig = daoConfigMap.get(Bean_PropertiesDao.class).clone();
        bean_PropertiesDaoConfig.initIdentityScope(type);

        bean_UserInfoDaoConfig = daoConfigMap.get(Bean_UserInfoDao.class).clone();
        bean_UserInfoDaoConfig.initIdentityScope(type);

        bean_PropertiesDao = new Bean_PropertiesDao(bean_PropertiesDaoConfig, this);
        bean_UserInfoDao = new Bean_UserInfoDao(bean_UserInfoDaoConfig, this);

        registerDao(Bean_Properties.class, bean_PropertiesDao);
        registerDao(Bean_UserInfo.class, bean_UserInfoDao);
    }
    
    public void clear() {
        bean_PropertiesDaoConfig.clearIdentityScope();
        bean_UserInfoDaoConfig.clearIdentityScope();
    }

    public Bean_PropertiesDao getBean_PropertiesDao() {
        return bean_PropertiesDao;
    }

    public Bean_UserInfoDao getBean_UserInfoDao() {
        return bean_UserInfoDao;
    }

}
